# Site settings
name: Jack's Blog
email: sunjie_310110@aliyun.com
author: Jack Sun
url: http://sunjie.me
#resume_site:
github: https://github.com/sunjiesh/
github_username: sunjiesh
baseurl: ""
description: Blog
meta_description: 个人博客系统
motto: 业精于勤而荒于嬉，行成于思而毁于随
banner: 业精于勤而荒于嬉，行成于思而毁于随

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: sunjiesh
highlighter: rouge

# Build settings
markdown: kramdown
